### PR TITLE
Update windows_installation.md

### PR DESCRIPTION
**Pull request by BinAccel**
Shamelessly copy-paste Tudor

### CODE REVIEW

**Comment by WallE256** [comment]
Remove the WSL related part, it's already covered in the Linux installation.

**Comment by Xyene** [comment]
I think it's worthwhile to keep, since users may not know about WSL or the fact that DMOJ can run on it. In case there are any WSL-specific issues with running judge (and there have been), it's good to have a section dedicated to it &mdash; even if these are instructions for Windows.

**Comment by BinAccel** [comment]
I was thinking of adding a link to the linux installation instructions

**Comment by quantum5** [comment]
Change to not use binaries.dmoj.ca, instead use [the automatic AppVeyor build](https://ci.appveyor.com/project/quantum5/judge/build/artifacts).

**Comment by BinAccel** [comment]
Does x86 /x64 even matter anymore?

**Comment by quantum5** [comment]
Yes, of course. But you do not use 32-bit python to run dmoj, because you won't be able to debug 64-bit applications.

**Comment by BinAccel** [comment]
The artifacts only has 64 bit, I think

**Comment by BinAccel** [comment]
So should I specifically say "This is 64 bit" or smth?

**Comment by BinAccel** [comment]
@quantum5 @Xyene plz proofread

**Comment by quantum5** [comment]
"from the official AppVeyor build" is bad. This is just an artifact of our current testing scheme and is in no way official whatsoever, especially since we do not provide any support for them.

**Comment by quantum5** [comment]
This documentation should probably say something about `_win_debugger.pyd`, although @Xyene, by virtue of being the author, should explain exactly what it is for.

**Comment by Xyene** [comment]
**mumble mumble** debugging magic that shouldn't work but does **mumble mumble**

---

It attaches a Ctrl+Break handler to the judge process such that when that command is executed, a `java`-style thread dump is printed to stdout. This is done by interfacing directly with Python guts and therefore isn't impeded by the GIL, meaning you can get a thread dump even if the process is deadlocked in native code (very useful!)

**Comment by BinAccel** [comment]
Where should this stuff about `_win_debugger.pyd` go @Xyene ?

**Comment by quantum5** [comment]
@BinAccel @Xyene please get this finished.

**Comment by WallE256** [comment]
@Xyene, it should be ok now. Please check

**Pull request merged**
